version: "3.8"

services:
  nextjs-app:
    build: .
    ports:
      - "3000:3000"   # Maps container port 3000 to host port 3000
    volumes:
      - .:/app         # Maps local code to container
    environment:
      - NODE_ENV=production
    user: "appuser"     # Ensures the container runs as the non-root user
    networks:
      - nextjs-network

networks:
  nextjs-network:
    driver: bridge
